{
  "swagger": "2.0",
  "host": "quay-jmfdr.apps.cluster-jmfdr.jmfdr.sandbox2884.opentlc.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "info": {
    "version": "v1",
    "title": "Quay Frontend",
    "description": "This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.",
    "termsOfService": "https://quay.io/tos",
    "contact": {
      "email": "support@quay.io"
    }
  },
  "securityDefinitions": {
    "oauth2_implicit": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://quay-jmfdr.apps.cluster-jmfdr.jmfdr.sandbox2884.opentlc.com/oauth/authorize",
      "scopes": {
        "repo:read": "This application will be able to view and pull all repositories visible to the granting user or robot account",
        "repo:write": "This application will be able to view, push and pull to all repositories to which the granting user or robot account has write access",
        "repo:admin": "This application will have administrator access to all repositories to which the granting user or robot account has access",
        "repo:create": "This application will be able to create repositories in to any namespaces that the granting user or robot account is allowed to create repositories",
        "user:read": "This application will be able to read user information such as username and email address.",
        "org:admin": "This application will be able to administer your organizations including creating robots, creating teams, adjusting team membership, and changing billing settings. You should have absolute trust in the requesting application before granting this permission.",
        "super:user": "This application will be able to administer your installation including managing users, managing organizations and other features found in the superuser panel. You should have absolute trust in the requesting application before granting this permission.",
        "user:admin": "This application will be able to administer your account including creating robots and granting them permissions to your repositories. You should have absolute trust in the requesting application before granting this permission."
      }
    }
  },
  "paths": {
    "/api/v1/user/apptoken": {
      "x-name": "endpoints.api.appspecifictokens.AppTokens",
      "x-path": "/api/v1/user/apptoken",
      "x-tag": "appspecifictokens",
      "post": {
        "operationId": "createAppToken",
        "description": "Create a new app specific token for user.",
        "tags": [
          "appspecifictokens"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listAppTokens",
        "description": "Lists the app specific tokens for the user.",
        "tags": [
          "appspecifictokens"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/apptoken/{token_uuid}": {
      "x-name": "endpoints.api.appspecifictokens.AppToken",
      "x-path": "/api/v1/user/apptoken/{token_uuid}",
      "x-tag": "appspecifictokens",
      "delete": {
        "operationId": "revokeAppToken",
        "description": "Revokes a specific app token for the user.",
        "tags": [
          "appspecifictokens"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getAppToken",
        "description": "Returns a specific app token for the user.",
        "tags": [
          "appspecifictokens"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/build/{build_uuid}/status": {
      "x-name": "endpoints.api.build.RepositoryBuildStatus",
      "x-path": "/api/v1/repository/{repository}/build/{build_uuid}/status",
      "x-tag": "build",
      "get": {
        "operationId": "getRepoBuildStatus",
        "description": "Return the status for the builds specified by the build uuids.",
        "tags": [
          "build"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/build/{build_uuid}/logs": {
      "x-name": "endpoints.api.build.RepositoryBuildLogs",
      "x-path": "/api/v1/repository/{repository}/build/{build_uuid}/logs",
      "x-tag": "build",
      "get": {
        "operationId": "getRepoBuildLogs",
        "description": "Return the build logs for the build specified by the build uuid.",
        "tags": [
          "build"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/build/{build_uuid}": {
      "x-name": "endpoints.api.build.RepositoryBuildResource",
      "x-path": "/api/v1/repository/{repository}/build/{build_uuid}",
      "x-tag": "build",
      "delete": {
        "operationId": "cancelRepoBuild",
        "description": "Cancels a repository build.",
        "tags": [
          "build"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getRepoBuild",
        "description": "Returns information about a build.",
        "tags": [
          "build"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/build/": {
      "x-name": "endpoints.api.build.RepositoryBuildList",
      "x-path": "/api/v1/repository/{repository}/build/",
      "x-tag": "build",
      "post": {
        "operationId": "requestRepoBuild",
        "description": "Request that a repository be built and pushed from the specified input.",
        "tags": [
          "build"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getRepoBuilds",
        "description": "Get the list of repository builds.",
        "tags": [
          "build"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/discovery": {
      "x-name": "endpoints.api.discovery.DiscoveryResource",
      "x-path": "/api/v1/discovery",
      "x-tag": "discovery",
      "get": {
        "operationId": "discovery",
        "description": "List all of the API endpoints available in the swagger API format.",
        "tags": [
          "discovery"
        ]
      }
    },
    "/api/v1/error/{error_type}": {
      "x-name": "endpoints.api.error.Error",
      "x-path": "/api/v1/error/{error_type}",
      "x-tag": "error",
      "get": {
        "operationId": "getErrorDescription",
        "description": "Get a detailed description of the error.",
        "tags": [
          "error"
        ]
      }
    },
    "/api/v1/messages": {
      "x-name": "endpoints.api.globalmessages.GlobalUserMessages",
      "x-path": "/api/v1/messages",
      "x-tag": "globalmessages",
      "post": {
        "operationId": "createGlobalMessage",
        "description": "Create a message.",
        "tags": [
          "globalmessages"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getGlobalMessages",
        "description": "Return a super users messages.",
        "tags": [
          "globalmessages"
        ]
      }
    },
    "/api/v1/message/{uuid}": {
      "x-name": "endpoints.api.globalmessages.GlobalUserMessage",
      "x-path": "/api/v1/message/{uuid}",
      "x-tag": "globalmessages",
      "delete": {
        "operationId": "deleteGlobalMessage",
        "description": "Delete a message.",
        "tags": [
          "globalmessages"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/user/aggregatelogs": {
      "x-name": "endpoints.api.logs.UserAggregateLogs",
      "x-path": "/api/v1/user/aggregatelogs",
      "x-tag": "logs",
      "get": {
        "operationId": "getAggregateUserLogs",
        "description": "Returns the aggregated logs for the current user.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/exportlogs": {
      "x-name": "endpoints.api.logs.ExportUserLogs",
      "x-path": "/api/v1/user/exportlogs",
      "x-tag": "logs",
      "post": {
        "operationId": "exportUserLogs",
        "description": "Returns the aggregated logs for the current user.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/logs": {
      "x-name": "endpoints.api.logs.UserLogs",
      "x-path": "/api/v1/user/logs",
      "x-tag": "logs",
      "get": {
        "operationId": "listUserLogs",
        "description": "List the logs for the current user.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/aggregatelogs": {
      "x-name": "endpoints.api.logs.OrgAggregateLogs",
      "x-path": "/api/v1/organization/{orgname}/aggregatelogs",
      "x-tag": "logs",
      "get": {
        "operationId": "getAggregateOrgLogs",
        "description": "Gets the aggregated logs for the specified organization.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/exportlogs": {
      "x-name": "endpoints.api.logs.ExportOrgLogs",
      "x-path": "/api/v1/organization/{orgname}/exportlogs",
      "x-tag": "logs",
      "post": {
        "operationId": "exportOrgLogs",
        "description": "Exports the logs for the specified organization.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/logs": {
      "x-name": "endpoints.api.logs.OrgLogs",
      "x-path": "/api/v1/organization/{orgname}/logs",
      "x-tag": "logs",
      "get": {
        "operationId": "listOrgLogs",
        "description": "List the logs for the specified organization.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/aggregatelogs": {
      "x-name": "endpoints.api.logs.RepositoryAggregateLogs",
      "x-path": "/api/v1/repository/{repository}/aggregatelogs",
      "x-tag": "logs",
      "get": {
        "operationId": "getAggregateRepoLogs",
        "description": "Returns the aggregated logs for the specified repository.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/exportlogs": {
      "x-name": "endpoints.api.logs.ExportRepositoryLogs",
      "x-path": "/api/v1/repository/{repository}/exportlogs",
      "x-tag": "logs",
      "post": {
        "operationId": "exportRepoLogs",
        "description": "Queues an export of the logs for the specified repository.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/logs": {
      "x-name": "endpoints.api.logs.RepositoryLogs",
      "x-path": "/api/v1/repository/{repository}/logs",
      "x-tag": "logs",
      "get": {
        "operationId": "listRepoLogs",
        "description": "List the logs for the specified repository.",
        "tags": [
          "logs"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}": {
      "x-name": "endpoints.api.manifest.ManageRepositoryManifestLabel",
      "x-path": "/api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}",
      "x-tag": "manifest",
      "delete": {
        "operationId": "deleteManifestLabel",
        "description": "Deletes an existing label from a manifest.",
        "tags": [
          "manifest"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getManifestLabel",
        "description": "Retrieves the label with the specific ID under the manifest.",
        "tags": [
          "manifest"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/manifest/{manifestref}/labels": {
      "x-name": "endpoints.api.manifest.RepositoryManifestLabels",
      "x-path": "/api/v1/repository/{repository}/manifest/{manifestref}/labels",
      "x-tag": "manifest",
      "post": {
        "operationId": "addManifestLabel",
        "description": "Adds a new label into the tag manifest.",
        "tags": [
          "manifest"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listManifestLabels",
        "description": "",
        "tags": [
          "manifest"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/manifest/{manifestref}": {
      "x-name": "endpoints.api.manifest.RepositoryManifest",
      "x-path": "/api/v1/repository/{repository}/manifest/{manifestref}",
      "x-tag": "manifest",
      "get": {
        "operationId": "getRepoManifest",
        "description": "",
        "tags": [
          "manifest"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/": {
      "x-name": "endpoints.api.organization.OrganizationList",
      "x-path": "/api/v1/organization/",
      "x-tag": "organization",
      "post": {
        "operationId": "createOrganization",
        "description": "Create a new organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/collaborators": {
      "x-name": "endpoints.api.organization.OrganizationCollaboratorList",
      "x-path": "/api/v1/organization/{orgname}/collaborators",
      "x-tag": "organization",
      "get": {
        "operationId": "getOrganizationCollaborators",
        "description": "List outside collaborators of the specified organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/applications/{client_id}": {
      "x-name": "endpoints.api.organization.OrganizationApplicationResource",
      "x-path": "/api/v1/organization/{orgname}/applications/{client_id}",
      "x-tag": "organization",
      "delete": {
        "operationId": "deleteOrganizationApplication",
        "description": "Deletes the application under this organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "updateOrganizationApplication",
        "description": "Updates an application under this organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getOrganizationApplication",
        "description": "Retrieves the application with the specified client_id under the specified organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/applications": {
      "x-name": "endpoints.api.organization.OrganizationApplications",
      "x-path": "/api/v1/organization/{orgname}/applications",
      "x-tag": "organization",
      "post": {
        "operationId": "createOrganizationApplication",
        "description": "Creates a new application under this organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getOrganizationApplications",
        "description": "List the applications for the specified organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/members/{membername}": {
      "x-name": "endpoints.api.organization.OrganizationMember",
      "x-path": "/api/v1/organization/{orgname}/members/{membername}",
      "x-tag": "organization",
      "delete": {
        "operationId": "removeOrganizationMember",
        "description": "Removes a member from an organization, revoking all its repository priviledges and removing\n        it from all teams in the organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getOrganizationMember",
        "description": "Retrieves the details of a member of the organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/members": {
      "x-name": "endpoints.api.organization.OrganizationMemberList",
      "x-path": "/api/v1/organization/{orgname}/members",
      "x-tag": "organization",
      "get": {
        "operationId": "getOrganizationMembers",
        "description": "List the human members of the specified organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}": {
      "x-name": "endpoints.api.organization.Organization",
      "x-path": "/api/v1/organization/{orgname}",
      "x-tag": "organization",
      "delete": {
        "operationId": "deleteAdminedOrganization",
        "description": "Deletes the specified organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "changeOrganizationDetails",
        "description": "Change the details for the specified organization.",
        "tags": [
          "organization"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getOrganization",
        "description": "Get the details for the specified organization.",
        "tags": [
          "organization"
        ]
      }
    },
    "/api/v1/app/{client_id}": {
      "x-name": "endpoints.api.organization.ApplicationInformation",
      "x-path": "/api/v1/app/{client_id}",
      "x-tag": "organization",
      "get": {
        "operationId": "getApplicationInformation",
        "description": "Get information on the specified application.",
        "tags": [
          "organization"
        ]
      }
    },
    "/api/v1/repository/{repository}/permissions/user/{username}/transitive": {
      "x-name": "endpoints.api.permission.RepositoryUserTransitivePermission",
      "x-path": "/api/v1/repository/{repository}/permissions/user/{username}/transitive",
      "x-tag": "permission",
      "get": {
        "operationId": "getUserTransitivePermission",
        "description": "Get the fetch the permission for the specified user.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/permissions/user/{username}": {
      "x-name": "endpoints.api.permission.RepositoryUserPermission",
      "x-path": "/api/v1/repository/{repository}/permissions/user/{username}",
      "x-tag": "permission",
      "delete": {
        "operationId": "deleteUserPermissions",
        "description": "Delete the permission for the user.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "changeUserPermissions",
        "description": "Update the perimssions for an existing repository.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getUserPermissions",
        "description": "Get the permission for the specified user.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/permissions/team/{teamname}": {
      "x-name": "endpoints.api.permission.RepositoryTeamPermission",
      "x-path": "/api/v1/repository/{repository}/permissions/team/{teamname}",
      "x-tag": "permission",
      "delete": {
        "operationId": "deleteTeamPermissions",
        "description": "Delete the permission for the specified team.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "changeTeamPermissions",
        "description": "Update the existing team permission.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getTeamPermissions",
        "description": "Fetch the permission for the specified team.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/permissions/team/": {
      "x-name": "endpoints.api.permission.RepositoryTeamPermissionList",
      "x-path": "/api/v1/repository/{repository}/permissions/team/",
      "x-tag": "permission",
      "get": {
        "operationId": "listRepoTeamPermissions",
        "description": "List all team permission.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/permissions/user/": {
      "x-name": "endpoints.api.permission.RepositoryUserPermissionList",
      "x-path": "/api/v1/repository/{repository}/permissions/user/",
      "x-tag": "permission",
      "get": {
        "operationId": "listRepoUserPermissions",
        "description": "List all user permissions.",
        "tags": [
          "permission"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/prototypes/{prototypeid}": {
      "x-name": "endpoints.api.prototype.PermissionPrototype",
      "x-path": "/api/v1/organization/{orgname}/prototypes/{prototypeid}",
      "x-tag": "prototype",
      "put": {
        "operationId": "updateOrganizationPrototypePermission",
        "description": "Update the role of an existing permission prototype.",
        "tags": [
          "prototype"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteOrganizationPrototypePermission",
        "description": "Delete an existing permission prototype.",
        "tags": [
          "prototype"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/prototypes": {
      "x-name": "endpoints.api.prototype.PermissionPrototypeList",
      "x-path": "/api/v1/organization/{orgname}/prototypes",
      "x-tag": "prototype",
      "post": {
        "operationId": "createOrganizationPrototypePermission",
        "description": "Create a new permission prototype.",
        "tags": [
          "prototype"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getOrganizationPrototypePermissions",
        "description": "List the existing prototypes for this organization.",
        "tags": [
          "prototype"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository": {
      "x-name": "endpoints.api.repository.RepositoryList",
      "x-path": "/api/v1/repository",
      "x-tag": "repository",
      "post": {
        "operationId": "createRepo",
        "description": "Create a new repository.",
        "tags": [
          "repository"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:create"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listRepos",
        "description": "Fetch the list of repositories visible to the current user under a variety of situations.",
        "tags": [
          "repository"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/changevisibility": {
      "x-name": "endpoints.api.repository.RepositoryVisibility",
      "x-path": "/api/v1/repository/{repository}/changevisibility",
      "x-tag": "repository",
      "post": {
        "operationId": "changeRepoVisibility",
        "description": "Change the visibility of a repository.",
        "tags": [
          "repository"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/changetrust": {
      "x-name": "endpoints.api.repository.RepositoryTrust",
      "x-path": "/api/v1/repository/{repository}/changetrust",
      "x-tag": "repository"
    },
    "/api/v1/repository/{repository}": {
      "x-name": "endpoints.api.repository.Repository",
      "x-path": "/api/v1/repository/{repository}",
      "x-tag": "repository",
      "delete": {
        "operationId": "deleteRepository",
        "description": "Delete a repository.",
        "tags": [
          "repository"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "updateRepo",
        "description": "Update the description in the specified repository.",
        "tags": [
          "repository"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getRepo",
        "description": "Fetch the specified repository.",
        "tags": [
          "repository"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/notification/{uuid}/test": {
      "x-name": "endpoints.api.repositorynotification.TestRepositoryNotification",
      "x-path": "/api/v1/repository/{repository}/notification/{uuid}/test",
      "x-tag": "repositorynotification",
      "post": {
        "operationId": "testRepoNotification",
        "description": "Queues a test notification for this repository.",
        "tags": [
          "repositorynotification"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/notification/{uuid}": {
      "x-name": "endpoints.api.repositorynotification.RepositoryNotification",
      "x-path": "/api/v1/repository/{repository}/notification/{uuid}",
      "x-tag": "repositorynotification",
      "post": {
        "operationId": "resetRepositoryNotificationFailures",
        "description": "Resets repository notification to 0 failures.",
        "tags": [
          "repositorynotification"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteRepoNotification",
        "description": "Deletes the specified notification.",
        "tags": [
          "repositorynotification"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getRepoNotification",
        "description": "Get information for the specified notification.",
        "tags": [
          "repositorynotification"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/notification/": {
      "x-name": "endpoints.api.repositorynotification.RepositoryNotificationList",
      "x-path": "/api/v1/repository/{repository}/notification/",
      "x-tag": "repositorynotification",
      "post": {
        "operationId": "createRepoNotification",
        "description": "",
        "tags": [
          "repositorynotification"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listRepoNotifications",
        "description": "List the notifications for the specified repository.",
        "tags": [
          "repositorynotification"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/tokens/{code}": {
      "x-name": "endpoints.api.repotoken.RepositoryToken",
      "x-path": "/api/v1/repository/{repository}/tokens/{code}",
      "x-tag": "repotoken",
      "delete": {
        "operationId": "deleteToken",
        "description": "Delete the repository token.",
        "tags": [
          "repotoken"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "changeToken",
        "description": "Update the permissions for the specified repository token.",
        "tags": [
          "repotoken"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getTokens",
        "description": "Fetch the specified repository token information.",
        "tags": [
          "repotoken"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/tokens/": {
      "x-name": "endpoints.api.repotoken.RepositoryTokenList",
      "x-path": "/api/v1/repository/{repository}/tokens/",
      "x-tag": "repotoken",
      "post": {
        "operationId": "createToken",
        "description": "Create a new repository token.",
        "tags": [
          "repotoken"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listRepoTokens",
        "description": "List the tokens for the specified repository.",
        "tags": [
          "repotoken"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/robots": {
      "x-name": "endpoints.api.robot.UserRobotList",
      "x-path": "/api/v1/user/robots",
      "x-tag": "robot",
      "get": {
        "operationId": "getUserRobots",
        "description": "List the available robots for the user.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/robots/{robot_shortname}/permissions": {
      "x-name": "endpoints.api.robot.OrgRobotPermissions",
      "x-path": "/api/v1/organization/{orgname}/robots/{robot_shortname}/permissions",
      "x-tag": "robot",
      "get": {
        "operationId": "getOrgRobotPermissions",
        "description": "Returns the list of repository permissions for the org's robot.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/robots/{robot_shortname}/regenerate": {
      "x-name": "endpoints.api.robot.RegenerateOrgRobot",
      "x-path": "/api/v1/organization/{orgname}/robots/{robot_shortname}/regenerate",
      "x-tag": "robot",
      "post": {
        "operationId": "regenerateOrgRobotToken",
        "description": "Regenerates the token for an organization robot.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/robots/{robot_shortname}/permissions": {
      "x-name": "endpoints.api.robot.UserRobotPermissions",
      "x-path": "/api/v1/user/robots/{robot_shortname}/permissions",
      "x-tag": "robot",
      "get": {
        "operationId": "getUserRobotPermissions",
        "description": "Returns the list of repository permissions for the user's robot.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/robots/{robot_shortname}/regenerate": {
      "x-name": "endpoints.api.robot.RegenerateUserRobot",
      "x-path": "/api/v1/user/robots/{robot_shortname}/regenerate",
      "x-tag": "robot",
      "post": {
        "operationId": "regenerateUserRobotToken",
        "description": "Regenerates the token for a user's robot.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/robots/{robot_shortname}": {
      "x-name": "endpoints.api.robot.OrgRobot",
      "x-path": "/api/v1/organization/{orgname}/robots/{robot_shortname}",
      "x-tag": "robot",
      "delete": {
        "operationId": "deleteOrgRobot",
        "description": "Delete an existing organization robot.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "createOrgRobot",
        "description": "Create a new robot in the organization.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getOrgRobot",
        "description": "Returns the organization's robot with the specified name.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/robots": {
      "x-name": "endpoints.api.robot.OrgRobotList",
      "x-path": "/api/v1/organization/{orgname}/robots",
      "x-tag": "robot",
      "get": {
        "operationId": "getOrgRobots",
        "description": "List the organization's robots.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/robots/{robot_shortname}": {
      "x-name": "endpoints.api.robot.UserRobot",
      "x-path": "/api/v1/user/robots/{robot_shortname}",
      "x-tag": "robot",
      "delete": {
        "operationId": "deleteUserRobot",
        "description": "Delete an existing robot.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "createUserRobot",
        "description": "Create a new user robot with the specified name.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getUserRobot",
        "description": "Returns the user's robot with the specified name.",
        "tags": [
          "robot"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/find/repositories": {
      "x-name": "endpoints.api.search.ConductRepositorySearch",
      "x-path": "/api/v1/find/repositories",
      "x-tag": "search",
      "get": {
        "operationId": "conductRepoSearch",
        "description": "Get a list of apps and repositories that match the specified query.",
        "tags": [
          "search"
        ]
      }
    },
    "/api/v1/find/all": {
      "x-name": "endpoints.api.search.ConductSearch",
      "x-path": "/api/v1/find/all",
      "x-tag": "search",
      "get": {
        "operationId": "conductSearch",
        "description": "Get a list of entities and resources that match the specified query.",
        "tags": [
          "search"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/entities/{prefix}": {
      "x-name": "endpoints.api.search.EntitySearch",
      "x-path": "/api/v1/entities/{prefix}",
      "x-tag": "search",
      "get": {
        "operationId": "getMatchingEntities",
        "description": "Get a list of entities that match the specified prefix.",
        "tags": [
          "search"
        ]
      }
    },
    "/api/v1/repository/{repository}/manifest/{manifestref}/security": {
      "x-name": "endpoints.api.secscan.RepositoryManifestSecurity",
      "x-path": "/api/v1/repository/{repository}/manifest/{manifestref}/security",
      "x-tag": "secscan",
      "get": {
        "operationId": "getRepoManifestSecurity",
        "description": "",
        "tags": [
          "secscan"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/users/": {
      "x-name": "endpoints.api.superuser.SuperUserList",
      "x-path": "/api/v1/superuser/users/",
      "x-tag": "superuser",
      "post": {
        "operationId": "createInstallUser",
        "description": "Creates a new user.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listAllUsers",
        "description": "Returns a list of all users in the system.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/logs": {
      "x-name": "endpoints.api.superuser.SuperUserLogs",
      "x-path": "/api/v1/superuser/logs",
      "x-tag": "superuser",
      "get": {
        "operationId": "listAllLogs",
        "description": "List the usage logs for the current system.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/keys": {
      "x-name": "endpoints.api.superuser.SuperUserServiceKeyManagement",
      "x-path": "/api/v1/superuser/keys",
      "x-tag": "superuser",
      "post": {
        "operationId": "createServiceKey",
        "description": "",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listServiceKeys",
        "description": "",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/organizations/{name}": {
      "x-name": "endpoints.api.superuser.SuperUserOrganizationManagement",
      "x-path": "/api/v1/superuser/organizations/{name}",
      "x-tag": "superuser",
      "put": {
        "operationId": "changeOrganization",
        "description": "Updates information about the specified user.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteOrganization",
        "description": "Deletes the specified organization.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/approvedkeys/{kid}": {
      "x-name": "endpoints.api.superuser.SuperUserServiceKeyApproval",
      "x-path": "/api/v1/superuser/approvedkeys/{kid}",
      "x-tag": "superuser",
      "post": {
        "operationId": "approveServiceKey",
        "description": "",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/keys/{kid}": {
      "x-name": "endpoints.api.superuser.SuperUserServiceKey",
      "x-path": "/api/v1/superuser/keys/{kid}",
      "x-tag": "superuser",
      "delete": {
        "operationId": "deleteServiceKey",
        "description": "",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      },
      "put": {
        "operationId": "updateServiceKey",
        "description": "",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getServiceKey",
        "description": "",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/{build_uuid}/status": {
      "x-name": "endpoints.api.superuser.SuperUserRepositoryBuildStatus",
      "x-path": "/api/v1/superuser/{build_uuid}/status",
      "x-tag": "superuser",
      "get": {
        "operationId": "getRepoBuildStatusSuperUser",
        "description": "Return the status for the builds specified by the build uuids.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/{build_uuid}/build": {
      "x-name": "endpoints.api.superuser.SuperUserRepositoryBuildResource",
      "x-path": "/api/v1/superuser/{build_uuid}/build",
      "x-tag": "superuser",
      "get": {
        "operationId": "getRepoBuildSuperUser",
        "description": "Returns information about a build.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/superuser/{build_uuid}/logs": {
      "x-name": "endpoints.api.superuser.SuperUserRepositoryBuildLogs",
      "x-path": "/api/v1/superuser/{build_uuid}/logs",
      "x-tag": "superuser",
      "get": {
        "operationId": "getRepoBuildLogsSuperUser",
        "description": "Return the build logs for the build specified by the build uuid.",
        "tags": [
          "superuser"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "super:user"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/tag/{tag}/restore": {
      "x-name": "endpoints.api.tag.RestoreTag",
      "x-path": "/api/v1/repository/{repository}/tag/{tag}/restore",
      "x-tag": "tag",
      "post": {
        "operationId": "restoreTag",
        "description": "Restores a repository tag back to a previous image in the repository.",
        "tags": [
          "tag"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:write"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/tag/{tag}": {
      "x-name": "endpoints.api.tag.RepositoryTag",
      "x-path": "/api/v1/repository/{repository}/tag/{tag}",
      "x-tag": "tag",
      "put": {
        "operationId": "changeTag",
        "description": "Change which image a tag points to or create a new tag.",
        "tags": [
          "tag"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteFullTag",
        "description": "Delete the specified repository tag.",
        "tags": [
          "tag"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:write"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/tag/": {
      "x-name": "endpoints.api.tag.ListRepositoryTags",
      "x-path": "/api/v1/repository/{repository}/tag/",
      "x-tag": "tag",
      "get": {
        "operationId": "listRepoTags",
        "description": "",
        "tags": [
          "tag"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/team/{teamname}/permissions": {
      "x-name": "endpoints.api.team.TeamPermissions",
      "x-path": "/api/v1/organization/{orgname}/team/{teamname}/permissions",
      "x-tag": "team",
      "get": {
        "operationId": "getOrganizationTeamPermissions",
        "description": "Returns the list of repository permissions for the org's team.",
        "tags": [
          "team"
        ]
      }
    },
    "/api/v1/organization/{orgname}/team/{teamname}/members/{membername}": {
      "x-name": "endpoints.api.team.TeamMember",
      "x-path": "/api/v1/organization/{orgname}/team/{teamname}/members/{membername}",
      "x-tag": "team",
      "put": {
        "operationId": "updateOrganizationTeamMember",
        "description": "Adds or invites a member to an existing team.",
        "tags": [
          "team"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteOrganizationTeamMember",
        "description": "Delete a member of a team.\n\n        If the user is merely invited to join the team, then the invite is removed instead.",
        "tags": [
          "team"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/team/{teamname}/members": {
      "x-name": "endpoints.api.team.TeamMemberList",
      "x-path": "/api/v1/organization/{orgname}/team/{teamname}/members",
      "x-tag": "team",
      "get": {
        "operationId": "getOrganizationTeamMembers",
        "description": "Retrieve the list of members for the specified team.",
        "tags": [
          "team"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/organization/{orgname}/team/{teamname}": {
      "x-name": "endpoints.api.team.OrganizationTeam",
      "x-path": "/api/v1/organization/{orgname}/team/{teamname}",
      "x-tag": "team",
      "put": {
        "operationId": "updateOrganizationTeam",
        "description": "Update the org-wide permission for the specified team.",
        "tags": [
          "team"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteOrganizationTeam",
        "description": "Delete the specified team.",
        "tags": [
          "team"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "org:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/trigger/{trigger_uuid}/activate": {
      "x-name": "endpoints.api.trigger.BuildTriggerActivate",
      "x-path": "/api/v1/repository/{repository}/trigger/{trigger_uuid}/activate",
      "x-tag": "trigger",
      "post": {
        "operationId": "activateBuildTrigger",
        "description": "Activate the specified build trigger.",
        "tags": [
          "trigger"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/trigger/{trigger_uuid}/builds": {
      "x-name": "endpoints.api.trigger.TriggerBuildList",
      "x-path": "/api/v1/repository/{repository}/trigger/{trigger_uuid}/builds",
      "x-tag": "trigger",
      "get": {
        "operationId": "listTriggerRecentBuilds",
        "description": "List the builds started by the specified trigger.",
        "tags": [
          "trigger"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/trigger/{trigger_uuid}/start": {
      "x-name": "endpoints.api.trigger.ActivateBuildTrigger",
      "x-path": "/api/v1/repository/{repository}/trigger/{trigger_uuid}/start",
      "x-tag": "trigger",
      "post": {
        "operationId": "manuallyStartBuildTrigger",
        "description": "Manually start a build from the specified trigger.",
        "tags": [
          "trigger"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/trigger/{trigger_uuid}": {
      "x-name": "endpoints.api.trigger.BuildTrigger",
      "x-path": "/api/v1/repository/{repository}/trigger/{trigger_uuid}",
      "x-tag": "trigger",
      "delete": {
        "operationId": "deleteBuildTrigger",
        "description": "Delete the specified build trigger.",
        "tags": [
          "trigger"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "put": {
        "operationId": "updateBuildTrigger",
        "description": "Updates the specified build trigger.",
        "tags": [
          "trigger"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getBuildTrigger",
        "description": "Get information for the specified build trigger.",
        "tags": [
          "trigger"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/repository/{repository}/trigger/": {
      "x-name": "endpoints.api.trigger.BuildTriggerList",
      "x-path": "/api/v1/repository/{repository}/trigger/",
      "x-tag": "trigger",
      "get": {
        "operationId": "listBuildTriggers",
        "description": "List the triggers for the specified repository.",
        "tags": [
          "trigger"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/starred": {
      "x-name": "endpoints.api.user.StarredRepositoryList",
      "x-path": "/api/v1/user/starred",
      "x-tag": "user",
      "post": {
        "operationId": "createStar",
        "description": "Star a repository.",
        "tags": [
          "user"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "repo:read"
            ]
          }
        ]
      },
      "get": {
        "operationId": "listStarredRepos",
        "description": "List all starred repositories.",
        "tags": [
          "user"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/user/": {
      "x-name": "endpoints.api.user.User",
      "x-path": "/api/v1/user/",
      "x-tag": "user",
      "get": {
        "operationId": "getLoggedInUser",
        "description": "Get user information for the authenticated user.",
        "tags": [
          "user"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:read"
            ]
          }
        ]
      }
    },
    "/api/v1/user/starred/{repository}": {
      "x-name": "endpoints.api.user.StarredRepository",
      "x-path": "/api/v1/user/starred/{repository}",
      "x-tag": "user",
      "delete": {
        "operationId": "deleteStar",
        "description": "Removes a star from a repository.",
        "tags": [
          "user"
        ],
        "security": [
          {
            "oauth2_implicit": [
              "user:admin"
            ]
          }
        ]
      }
    },
    "/api/v1/users/{username}": {
      "x-name": "endpoints.api.user.Users",
      "x-path": "/api/v1/users/{username}",
      "x-tag": "user",
      "get": {
        "operationId": "getUserInformation",
        "description": "Get user information for the specified user.",
        "tags": [
          "user"
        ]
      }
    },
    "/userfiles/{file_id}": {
      "x-name": "data.userfiles.UserfilesHandlers",
      "x-path": "/userfiles/{file_id}",
      "x-tag": "userfiles"
    }
  },
  "tags": [
    {
      "name": "appspecifictokens",
      "description": "Manages app specific tokens for the current user."
    },
    {
      "name": "build",
      "description": "Create, list, cancel and get status/logs of repository builds."
    },
    {
      "name": "discovery",
      "description": "API discovery information."
    },
    {
      "name": "error",
      "description": "Error details API."
    },
    {
      "name": "globalmessages",
      "description": "Messages API."
    },
    {
      "name": "logs",
      "description": "Access usage logs for organizations or repositories."
    },
    {
      "name": "manifest",
      "description": "Manage the manifests of a repository."
    },
    {
      "name": "organization",
      "description": "Manage organizations, members and OAuth applications."
    },
    {
      "name": "permission",
      "description": "Manage repository permissions."
    },
    {
      "name": "prototype",
      "description": "Manage default permissions added to repositories."
    },
    {
      "name": "repository",
      "description": "List, create and manage repositories."
    },
    {
      "name": "repositorynotification",
      "description": "List, create and manage repository events/notifications."
    },
    {
      "name": "repotoken",
      "description": "Manage repository access tokens (DEPRECATED)."
    },
    {
      "name": "robot",
      "description": "Manage user and organization robot accounts."
    },
    {
      "name": "search",
      "description": "Conduct searches against all registry context."
    },
    {
      "name": "secscan",
      "description": "List and manage repository vulnerabilities and other security information."
    },
    {
      "name": "superuser",
      "description": "Superuser API."
    },
    {
      "name": "tag",
      "description": "Manage the tags of a repository."
    },
    {
      "name": "team",
      "description": "Create, list and manage an organization's teams."
    },
    {
      "name": "trigger",
      "description": "Create, list and manage build triggers."
    },
    {
      "name": "user",
      "description": "Manage the current user."
    },
    {
      "name": "userfiles",
      "description": ""
    }
  ]
}
