apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: developer-hub
  description: An internal developer portal providing a Software Catalog and integrations.
  links:
    - url: https://backstage-backstage{{ cluster_subdomain }}
      title: Developer Hub
spec:
  type: dev-service
  tags:
    - nodejs
  lifecycle: production
  owner: group:rhdh
  system: default/dev-cluster-services
  dependsOn:
    - resource:default/developer-hub-postgres
    - resource:default/openshift-api-server
    - resource:default/quay
    - resource:default/developer-hub-gitops
  consumesApis:
    - api:default/openshift-cluster-api
    - api:default/quay-api