apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: gitlab
  description: Git repository and CI platform.
  links:
    - url: https://{{ gitlab_host }}
      title: GitLab Console
spec:
  type: dev-service
  lifecycle: production
  owner: group:rhdh
  system: default/dev-cluster-services
  dependsOn:
    - resource:default/developer-hub-postgres
    - resource:default/openshift-api-server
    - resource:default/quay
    - resource:default/developer-hub-gitops