apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: developer-hub-gitops
  description: OpenShift GitOps (Argo CD) cluster used to manage developer workloads.
  links:
    - url: https://argocd-server-janus-argocd{{ cluster_subdomain }}
      title: Developer GitOps
spec:
  type: dev-service
  lifecycle: production
  owner: group:rhdh
  system: default/dev-cluster-services
  consumesApis:
    - api:default/openshift-cluster-api