apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: openshift-api-server
  description: The API server for the OpenShift cluster.
spec:
  type: service
  lifecycle: production
  owner: group:rhdh
  providesApis:
    - api:default/openshift-cluster-api
  system: default/dev-cluster-services
    