apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: openshift-pipelines
  description: A Kubernetes-native CI/CD system based on Tekton Pipelines.
spec:
  type: service
  lifecycle: production
  owner: group:rhdh
  system: default/dev-cluster-services
  consumesApis:
    - api:default/quay-api