apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: openshift-gitops
  description: OpenShift GitOps (Argo CD) cluster used to manage infrastructure.
  annotations:
    gitlab.com/instance: ''
    gitlab.com/project-slug: ''
    gitlab.com/project-id: ''
  links:
  - url: https://argocd-server-openshift-gitops{{ cluster_subdomain }}
    title: Infrastructure GitOps
spec:
  type: service
  lifecycle: production
  owner: group:rhdh
  system: default/dev-cluster-services
  consumesApis:
    - api:default/openshift-cluster-api