apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: quay
  description: A container image registry service.
  links:
    - url: https://{{ quay_host }}
      title: Quay Console
spec:
  type: image-registry
  lifecycle: production
  owner: group:rhdh
  system: default/dev-cluster-services
  providesApis:
    - api:default/quay-api